# 本文件是更改默认渲染显卡的示例
# 请在 mpv 配置文件夹运行 'cp device.exapmle.conf device.conf'
# 并自行更改 device.conf 的设置

## 操作系统相关
# [自用] Linux 配置
# gpu-api = vulkan
# ao = pipewire
# [自用] Windows 配置
# gpu-api = d3d11
# snap-window = yes                     # [Windows独占] 贴边吸附
# ao = wasapi

## input.conf 位置设置
# input-conf = "~~/input.conf"          # Linux
# input-conf = "~~/input_windows.conf"  # Windows
                                        # 额外加载 自定义快捷键 的配置文件

## 多显卡设置(请自行更改显卡名称)
# d3d11-adapter = 'NVIDIA GeForce RTX 4060 Laptop GPU'
                                        # [当 --gpu-api=d3d11 时] 指定某张显卡作为主渲染输出，名称看任务管理器
                                        # (如果是不同品牌的显卡) 可以以厂商名称开头 <AMD|Intel|NVDIA>
                                        # 命令行运行 mpv --d3d11-adapter=help 会列出所有可用的设备
# vulkan-device = 'NVIDIA GeForce RTX 4060 Laptop GPU'
                                        # [当 --gpu-api=vulkan 时] 大体上和 --d3d11-adapter 相同
                                        # 但是需要写完整名
                                        # 命令行运行 mpv --vulkan-device=help 会列出所有可用的设备
