# 本文件是更改默认渲染显卡的示例
# 请在 mpv 配置文件夹运行 'cp device.exapmle.conf device.conf'
# 并自行更改设置

## 多显卡设置(请自行更改显卡名称)
# d3d11-adapter = 'NVIDIA GeForce RTX 4060 Laptop GPU'
                                        # [当 --gpu-api=d3d11 时] 指定某张显卡作为主渲染输出，名称看任务管理器
                                        # (如果是不同品牌的显卡) 可以以厂商名称开头 <AMD|Intel|NVDIA>
                                        # 命令行运行 mpv --d3d11-adapter=help 会列出所有可用的设备
# vulkan-device = 'NVIDIA GeForce RTX 4060 Laptop GPU'
                                        # [当 --gpu-api=vulkan 时] 大体上和 --d3d11-adapter 相同
                                        # 但是需要写完整名
                                        # 命令行运行 mpv --vulkan-device=help 会列出所有可用的设备
