# 类似于 device.exapmle.conf
# 但不同的是，你需要运行：
# cp file_browser.example.conf script-opts/file_browser.conf

# root directories, separated by commas
# on linux you will probably want to add `/`,
# on windows this should be used to add different drive letters
# Examples:
# linux:     root=~/,/
# windows:   root=~/,C:/
# root=~/,/,/mnt/,/run/media/
# root=~/,C:/,D:/
