# 本文件是更改默认渲染显卡的示例
# 请在 mpv 配置文件夹运行 'cp proxy.exapmle.conf proxy.conf'
# 并自行更改 proxy.conf 的设置

## 代理
# * 亦可使用 环境变量 + 系统代理 的方式，环境变量参见：https://mpv.io/manual/master/#environment-variables-http-proxy
# http-proxy = http://127.0.0.1:7890
# ytdl-raw-options-append = proxy=http://127.0.0.1:7890
                                        # 让 yt-dlp 使用代理
                                        # 此项的值会被传递给 mpv，所以也只能使用 http(s) 代理
