# 是否自动显示弹幕
autoplay=yes
# 最小弹幕数量
mincount=1
# 弹幕字体
fontname=Noto Sans CJK SC
# 弹幕字体大小 
fontsize=40
# 弹幕不透明度(0-1)
opacity=0.60
# 滚动弹幕显示的持续时间 (秒)
duration_marquee=10
# 静止弹幕显示的持续时间 (秒)
duration_still=5
# 保留底部多少高度的空白区域 (取值0.0-1.0)
percent=0.75
# 弹幕屏蔽的关键词文件路径，支持绝对和相对路径
filter_file=
# 是否对低帧率视频自动添加fps滤镜，以保证滚动弹幕流畅
fps_vf=yes
# 是否在osd显示日志
log_osd=no
# 是否使用Danmu2Ass.py，为false时使用Danmu2Ass.exe
use_python=yes
# python可执行文件路径，默认为环境变量的python，若无法运行请指定 python[.exe] 的路径
python_path=python